name: jasonread

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:
 build:
    runs-on: ubuntu-latest

    steps:  
      - name: checking out repo
        uses: actions/checkout@v3
      - name: build the schema and validate the data
        uses: Deepakthreat/workflowactiontm/tm-actions/DotNet.GitHubAction@main
        id: validation
        with:
          main_schema_path: ${{ github.workspace }}/WebServerEIPCfn_Secure.json

 

   
