name: jasonread

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:
 build:
    runs-on: ubuntu-latest

    steps:  
      - name: checking out repo
        uses: actions/checkout@v3
      - name: build the schema and validate the data
        uses: Deepakthreat/workflowactiontm/tm-actions/DotNet.GitHubAction@main
        env:
         GREETINGS: 'Hello, .NET developers!' # ${{ secrets.GITHUB_TOKEN }}
        with:
         owner: ${{ github.repository_owner }}
         name: ${{ github.repository }}
         branch: ${{ github.ref }}
         dir: ${{ './tm-actions/DotNet.GitHubAction' }}
    
      - id: set_var
        run: |
          content=`cat ./tm-actions/DotNet.GitHubAction/cloudformation/WebServerEIPCfn_Secure.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"    
          # end of optional handling for multi line json
          echo "::set-output name=Jsonvalue::$content"
      - name: "Set data"
        run: |
          env_data=${{ fromJson(steps.set_var.outputs.Jsonvalue).[0].AWSTemplateFormatVersion }}
          echo "env_data=$env_data"
          echo $env_data
