name: jasonread

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:
 build:
    runs-on: ubuntu-latest

    steps:  
     - name: fetch the json value
       run: |
         githubjson=`cat Deepakthreat/workflowactiontm/tm-actions/DotNet.GitHubAction/cloudformation/WebServerEIPCfn_Secure.json`
         echo $githubjson
         number=`echo $(jq -r '.number' <<< "$githubjson")`
         PRTitle=`echo $(jq -r '.pull_request.title' <<< "$githubjson")`
         PRUrl=`echo $(jq -r '.pull_request.html_url' <<< "$githubjson")`
         PRBody=`echo $(jq -r '.pull_request.body' <<< "$githubjson")`

 

   
